### ISSUE TITLE
ValueError: no tags in file

### ISSUE THREAD

**Issue by georf** [brokkr/poca#101]
Hi there,

I got an other error while downloading the following feed:
http://web.ard.de/radiotatort/rss/podcast.xml

```
 ⇵ 2011_podcast_abschaum.mp3  [50 Mb]
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.4/dist-packages/poca/subupgrade.py", line 26, in run
    sub_upgrade = self.target(self.subdata)
  File "/usr/local/lib/python3.4/dist-packages/poca/subupgrade.py", line 52, in __init__
    self.acquire(uid, entry, subdata)
  File "/usr/local/lib/python3.4/dist-packages/poca/subupgrade.py", line 99, in acquire
    subdata.sub, subdata.jar, entry)
  File "/usr/local/lib/python3.4/dist-packages/poca/tag.py", line 60, in tag_audio_file
    audio.save(v1=id3v1, v2_version=id3v2)
  File "/usr/lib/python3/dist-packages/mutagen/_file.py", line 111, in save
    raise ValueError("no tags in file")
ValueError: no tags in file
```

If I tried to download again the file wasn't download again. So it doesn't hurt me very much, but perhaps it's an issue.

**Comment by brokkr** [comment]
Well, you're right that there's something wrong with this file. However poca should be able to detect when id3 headers are missing and create some itself. Which seems to be what's happening here on my side. Can you give me the general id3 settings from your config and the specific metadata settings for the Tatort feed?

**Comment by brokkr** [comment]
I'm thking it's the same as [this one}(https://github.com/quodlibet/mutagen/issues/227)

This would be relevant if you did not add any metadata overrides to the feed, either in the defaults or in the feed's own settings.

Basically, if an mp3 has an empty id3 header (no tags) and the user doesn't add any tags, we try to save an empty header. And while there's nothing wrong with an empty header, mutagen apparently doesn't like. Solution: Don't do tagging if the user have no overrides.

I have put that attempt at a solution into beta10. Crossing fingers that will do the trick :)

**Comment by georf** [comment]
You are right, i didn't have defined metadata for this podcast. I updated to the version beta10 and added this podcast again. This time it downloaded it without trouble. Thanks! :+1:
