### ISSUE TITLE
Is is possible to set a download starting point?

### ISSUE THREAD

**Issue by wtanksleyjr** [brokkr/poca#161]
As someone who's switching podcatchers, I've got some long serials for which I already have most of the feed. I'd like to start from a given point, either an episode number or a date.

In service of that, is there a command to display all currently known episodes of a given feed?

**Comment by brokkr** [comment]
You mean known as in known to poca? Afraid not. You can always check the folder but of course currently on file does not equal known. In poca 2.0 (currently sort of ish in development) the db will simply be a very human readable yaml file which should do what you're looking for AFAICT.

However, for what you're looking for, I take it you already know about the [after date](https://poca.readthedocs.io/en/latest/Subscriptions.html#after-date) subscription setting? I would use that combined with a max_number of say 3 and test that poca only gets the episodes you don't already have. Once that's verified lift the max_number to however many you need or remove it to get everything from after the date in question.

**Comment by wtanksleyjr** [comment]
Ahhh, the `after date` setting will do nicely! Thank you!

**Comment by wtanksleyjr** [comment]
Actually, is it possible that after_date doesn't work when combined with from_the_top? I'm just not able to make it work at all.

**Comment by brokkr** [comment]
I am unable to reproduce the error with poca 1.1 installed from pip on Ubuntu 20.04 (python 3.8.10).

Here's what I did to test:

1. Create a temporary virtual environment, so a clean slate
2. pip3 install poca
3. poca-subscribe --config ./pocaconf/ (get fresh config in the virtual environment dir)
4. poca-subscribe --config ./pocaconf/ add
5. Put in https://feeds.megaphone.fm/SLT6250292033 (a very long running feed of over 700 entries back to 2006)
6. Enter 3 as max number 
7. Say yes to from the top
8. Run it (poca --config ./pocaconf/)
9. Watch it get the three first episodes from 2006
10. Edit ./pocaconf/poca.xml
11. add `<filters><after_date>2016-12-01</after_date></filters>` to the subscribtion
12. Save and quit
12. Run it again (poca --config ./pocaconf/)
13. Watch it delete the three first episodes and get episodes from December 6th, 13th and 20th 2016 instead.

Can I ask you to check the syntax? In previous testing (#123) I myself have gotten it wrong by not using the correct syntax. If you're sure that it's correct, can I ask you to supply the feed and your filters as written in poca.xml?

**Comment by wtanksleyjr** [comment]
You're right, it was pure syntax messup on my part; I copied your filter section, made minimal modification, and boom it all worked. Thank you!
