### ISSUE TITLE
SyntaxError: (unicode error) 'unicodeescape'

### ISSUE THREAD

**Issue by georf** [brokkr/poca#93]
Hello, I got the following error, while starting poca:
```
Traceback (most recent call last):
  File "/usr/local/bin/poca", line 18, in <module>
    import poco
  File "/usr/local/lib/python3.4/dist-packages/poco/__init__.py", line 15, in <module>
    from . import output
  File "/usr/local/lib/python3.4/dist-packages/poco/output.py", line 104
    msg = ' ' + "\N{CANCELLATION X}" + ' ' + entry['poca_filename'] + size_str
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 0-17: unknown Unicode character name
```

What did I wrong?

**Comment by brokkr** [comment]
Hi, thanks for the bug report. Can I ask you to tell me:
* What version of poca are you using? A specific release or did you clone the repo (if so when about)?
* What distro are you on?
* What shell do you use?
* What's your locale and language? (Do `echo $LOCALE $LANG` in your terminal)

**Comment by georf** [comment]
I cloned the repo yesterday: `git clone https://github.com/brokkr/poca/`
My last commit is 9d0d06c627712993bb14dea43249b2941feb206f

I use Armbian with bash:
```
# uname -a
Linux truck 3.4.113-sun7i #23 SMP PREEMPT Wed Jun 14 23:57:45 CEST 2017 armv7l GNU/Linux

# bash --version
GNU bash, version 4.3.30(1)-release (arm-unknown-linux-gnueabihf)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

# echo $LOCALE $LANG
C.UTF-8

# python3 --version
Python 3.4.2
```

**Comment by brokkr** [comment]
Thanks. I'm unable to replicate the error but I suspect that the python version is the critical issue here. If you can open up a python3 session (just enter a `python3` command on your terminal), enter the following and tell me what it says that would be a big help:

    import unicodedata
    print(unicodedata.unidata_version)
    unicodedata.name('🗙')

**Comment by georf** [comment]
Thank you for your reply. I tested your code:

```
>>> print(unicodedata.unidata_version)
6.3.0
>>> unicodedata.name('🗙')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: no such name
>>> print('\U0001f5d9')
🗙
```

So I think you are on the right way.

**Comment by brokkr** [comment]
Excellent, thank you so much. I'm hoping to put out a version 1.0 in the coming days so finding these issues now is really good. 

I'm going to put the fix into my development branch tomorrow and I'm hoping to merge it into master before the end of the week. I'll close this issue and let you know when that happens.

**Comment by brokkr** [comment]
Fixed in master: Substututed code points for unicode character names.

**Comment by georf** [comment]
Okay. Thanks. It starts now. I notices other things, but I will open a new issue
